### ISSUE TITLE
Add pathogen-ci to ci

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/rsv#26] opened 2023-05-15 22:07 UTC
### Context
Pathogen CI has become quite useful to test compatibility of new augur features, and to check that docker images and conda environments are compatible.

It would be nice to add example data so that this workflow can be easily tested within the remit of pathogen ci.

**Comment by tsibley** [comment] 2023-05-22 21:29
Duplicate of #27.

**Closed by tsibley** 2023-05-22 21:29 UTC
