### ISSUE TITLE
CI failure: nextclade3 command not found

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/rsv#50] opened 2023-12-20 00:45 UTC
Failure observed from [Augur PR 1348](https://github.com/nextstrain/augur/pull/1348) while it ran it's pathogen-repo-rsv workflow. Error:
```
 /home/runner/micromamba/envs/augur/bin/bash: line 2: nextclade3: command not found
```

([Direct link](https://github.com/nextstrain/augur/actions/runs/7268762064/job/19805203717) to the failing CI job)

I haven't investigated more. Tagging @corneliusroemer as I know you're on top of the migration here!

**Comment by corneliusroemer** [comment] 2023-12-20 08:38
Expected failure due to lack of Nextclade 3 in conda, not a bug

Docker passes

**Comment by victorlin** [comment] 2023-12-22 22:43
Fixed by https://github.com/nextstrain/conda-base/pull/50.

**Closed by victorlin** 2023-12-22 22:43 UTC
Labels: bug
